### ISSUE TITLE
mapbox tiles not loading with default configuration file

### ISSUE THREAD

**Issue by lostground** [forensic-architecture/timemap#106]
Environment
-----------
I am using the develop branch of timemap. This issue has appeared both in Firefox 60.6.1esr and Chromium 73.0.3683.75 running on openSUSE Leap 15. 

Current Behavior
----------------
After including my mapbox API key in the default config.js file and compiling timemap with yarn no map tiles are loaded in my browser, just a grey screen. 
![image](https://user-images.githubusercontent.com/45695140/57132613-03ef9400-6d98-11e9-93b8-ecf3977e1471.png)

Commenting out `MAPBOX_TOKEN:` causes OSM map tiles to be loaded without a problem as is stated in the "Reguirements" section of the readme.

After including a `tiles: 'satellite'` or `tiles: 'street'` attribute in the `store` of config.js, mapbox tiles are loaded as expected (see the working example below). I suggest to include this `tiles:` attribute in default config.js file.
```
store: {
    app: {
      map: {
        anchor: [50.9344, 1.8628]
      },
      timeline: {
        range: [
          new Date(2014, 7, 9),
          new Date(2014, 10, 6, 23)
        ],
        rangeLimits: [
          new Date(2014, 1, 1),
          new Date(2018, 1, 6, 23)
        ]
      }
    },
    ui: {
      tiles: 'satellite', // ['openstreetmap', 'streets', 'satellite']
      style: {
        categories: {},
        shapes: {},
        narratives: {},
        selectedEvent: {}
      }
    }
}
```
Edited to remove the comment slashes before `tiles: 'satellite', // ['openstreetmap', 'streets', 'satellite']`

**Comment by breezykermo** [comment]
@lostground, was there a solution here, or did you realise it was an issue somewhere else?

**Comment by lostground** [comment]
The solution is to include the `tiles` attribute with a value of either `openstreetmap`, `streets` or `satellite` within `ui: {}` in config.js.

Example:
```
ui: {
      tiles: 'satellite', // ['openstreetmap', 'streets', 'satellite']
      style: {
        categories: {},
        shapes: {},
        narratives: {},
        selectedEvent: {}
      }
```

**Comment by breezykermo** [comment]
This is fixed by 3e439d89a6c2ef717152c4068a80830f40e503f2.

**Comment by lostground** [comment]
Mapbox tiles are again failing to load by just editing the new example [configuration file](https://github.com/forensic-architecture/timemap/blob/develop/example.config.js) from commit [842bda5](https://github.com/forensic-architecture/timemap/commit/842bda5e1228046460b5a378d42c5a2b5a99e286). The fact that `tiles` is located within `style` means that the value cannot be read correctly when it is called in timemap/components/Map.jsx.

Proposed fix:
```
    ui: {
      // tiles: 'your-mapbox-account-name/x5678-map-id', 
      style: {       
      }
    },
```
//

**Comment by breezykermo** [comment]
Thanks @lostground! I've just merged a fix.
