### ISSUE TITLE
events not displaying - issue with shapes?

### ISSUE THREAD

**Issue by lostground** [forensic-architecture/timemap#107]
When loading a timemap instance, I get a popup error that says "Some URLs returned negative. If you are in development, check the server is running". After clicking OK the map tiles load, but no events or locations are displayed in the timeline or on the map.

I am using the datasheet-server example, and see that when timemap queries the server for `export_shapes` it doesn't find anything - `GET /api/example/export_shapes/columns 404 2.672 ms - 92` (see image below). 

![Screenshot_20190510_122519](https://user-images.githubusercontent.com/45695140/57524284-47f61200-731f-11e9-9f09-e7a4d19cf88a.png)

Changing the value of `USE_SHAPES` to `false` in timemap's `config.js` or deleting the line `SHAPES_EXT: '/api/example/export_shapes/columns',` (the first thing I did was try to disable all features to get a minimal working instance) breaks timemap completely. The page flashes up for a split second (without the popup error!) and then just goes completely black. 

Here are my console errors logs using Chromium when this happens:
[localhost-1557502626315.log](https://github.com/forensic-architecture/timemap/files/3167258/localhost-1557502626315.log)
The first two errors `Error: <rect> attribute width: A negative value is not valid. ("-300")` appear when the page flashes briefly, and the other three (`react-dom.production.min.js:179 TypeError: Cannot read property 'map' of undefined`, `react-dom.production.min.js:179 TypeError: Cannot read property 'map' of undefined`, and `index.js:41 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined`) appear when it goes black.

Is there any more information on what `shapes` are or how they are used by datasheet server and timemap? I see that there is no `EXPORT_SHAPES` tab in the GoogleSheet which might be expected (what information would it include?), but it is also not present in the `tabs` section of  `sheets_config.js` of datasheet-server. Why is timemap querying `shapes` and why would disabling the `USE_SHAPES` feature result in timemap failing to load anything?

**Comment by lostground** [comment]
Solved: these errors were a symptom of something else...

Checking back through the [readme](https://github.com/forensic-architecture/timemap/blob/develop/README.md) I saw that a `tags` field is required for events. In the Datasheet Server || Timemap Example GoogleSheet there are no tags. Making a number of sequentially numbered tag columns in the export_events GoogleSheet tab resolved the issues. I now have a working instance of Timemap!

This should be addressed in #97

**Comment by breezykermo** [comment]
Thanks for this @lostground! I've added two example tags to the example sheet to prevent this happening in the future as well, as it's actually an issue with the _example sheet_ (rather than Timemap).

See: https://docs.google.com/spreadsheets/d/1UC7DkCFeUXHfpUxUGruExwFbP4pqVBdJLOKfo6wDDGk/edit#gid=203003750
