### ISSUE TITLE
Add support for narrative sequences of events

### ISSUE THREAD

**Issue by francamps** [forensic-architecture/timemap#11]
Adding support for displaying an event as logical followup to a previous event would allow to link events in logical and narrative sequences. This can be represented in a variety of ways, some of which are complementary:

* Events that are linked within a narrative sequence and follow each other would be visually bound by a directional edge.
* Selecting a time span in the timeline would filter events in the narrative sequence, displaying only those that fall within the displayed time bounds. This means at any given time zoom, TimeMap will only show those events in a narrative sequence that fall within those bounds, potentially leaving out some in the past or in the future.
* Cards with event metadata that, displayed on click, could show a 'Next'-like button that would let the user follow this sequence step by step.
* In the future, events that are linked within narrative sequences could show this in some form in the timeline also.

**Comment by francamps** [comment]
Issue to discuss: what happens if some tags are selected that filter some, but not all, events in a narrative sequence? Say the original sequence contains the following events.

```
EvA -> EvB -> EvC -> EvD
```

And on selecting Tag 0B, EvB is no longer displayable, and now only the following are visible:

```
EvA -> ___ -> EvC -> EvD
```

* Does the lines joining EvA to EvB to EvC now collapse onto a direct edge from EvA to EvC?
* Similarly, does a 'Next' button on the Card EvA now take you straight to Ev?

**Comment by breezykermo** [comment]
Hmm, would it be possible to "grey out" events that don't fall in selected tags when a narrative is active? I think it makes sense to keep all events in a narrative visible when it is selected.

Another option would be to disable searching by tags entirely when a narrative is selected. In other words. This might actually be the cleanest solution?
