### ISSUE TITLE
Search Bar feature plan

### ISSUE THREAD

**Issue by sol-austin** [forensic-architecture/timemap#150]
I'd like to add a search bar to timemap to help users find events quickly. 

`Search.js` would be in `src/components` and called from `Layout.js`.

I would add the following methods to `Layout.js` and pass them down to the SearchBar component:
onQueryUpdate - invoked when the enter key is pressed to submit the search field or when the search field input changes. . I'd create a new reducer to handle this called `UPDATE_SEARCH_QUERY`. The search query itself needs to be stored in the app state to make the app serializable, so the results can't just be stored in the state. I'd also create a new reducer called `UPDATE_SEARCH_RESULTS` which would be an array, similar to the array at `appState.domain.events`, but only containing any events with names containing the search query.

onSearchStateUpdate - invoked when the search results state changes. This will be a method passed down to the map and timeline child components returning the search query results from the state instead of `appState.domain.events`. 

The map and timeline components will need to be modified to use the search query app state when appropriate, however the onSearchStateUpdate method should provide most of this functionality.

**Comment by breezykermo** [comment]
In the first iteration, let's not add any new data structure for search results, and instead just issue an `UPDATE_SELECTED` action when an event or a set of events are chosen from the search panel.
