### ISSUE TITLE
Update react-redux dependency

### ISSUE THREAD

**Issue by wattroll** [forensic-architecture/timemap#239]
Now that `react` was updated to 18 (#233), it would make sense to also update `react-redux` to 7.

It seems to work OK when I bump it, but I am not very familiar with this codebase and haven't been using react-redux before, so I don't have a good intuition of what needs to be payed attention to when jumping a few major versions. It would be safer if somebody who does could have a look at this. 

Just bringing this up, because of a need for `useSelector` [here](https://github.com/bellingcat/ukraine-timemap/pull/33/files#diff-8bd7ccf93aeb8a9f6754bf104bcef088cd832d51f3cfa129c226351d449ea166R56-R65). Thanks.

**Comment by breezykermo** [comment]
Yes, we should update this. Would you be interested in opening a PR to do so?

**Comment by jstolwijk** [comment]
I can pick this one up if no objections ;)

**Comment by breezykermo** [comment]
Sounds good to me, thanks @jstolwijk!

**Comment by wattroll** [comment]
@jstolwijk Thanks a lot!
