### ISSUE TITLE
Installation Error, Help!!

### ISSUE THREAD

**Issue by ryan0802** [forensic-architecture/timemap#266]
OS: Ubuntu 22.04
Node Version : v6.17.1
NPM Version : 3.10.10
NVM Version : 0.39.3

I tried to install timemap on my environment above, 
but error occured. please help.

[npm-debug.log](https://github.com/forensic-architecture/timemap/files/15141093/npm-debug.log)

│ └─┬ watchpack@1.7.5 
│   └─┬ watchpack-chokidar2@2.0.1 
│     └─┬ chokidar@2.1.8 
│       ├─┬ anymatch@2.0.0 
│       │ ├── micromatch@3.1.10 
│       │ └── normalize-path@2.1.1 
│       ├─┬ braces@2.3.2 
│       │ ├── extend-shallow@2.0.1 
│       │ └─┬ fill-range@4.0.0 
│       │   ├── extend-shallow@2.0.1 
│       │   ├─┬ is-number@3.0.0 
│       │   │ └── kind-of@3.2.2 
│       │   └── to-regex-range@2.1.1 
│       ├─┬ glob-parent@3.1.0 
│       │ └── is-glob@3.1.0 
│       ├─┬ is-binary-path@1.0.1 
│       │ └── binary-extensions@1.13.1 
│       └── readdirp@2.2.1 
├── UNMET DEPENDENCY webpack-dev-server@3.11.0
├── UNMET PEER DEPENDENCY webpack-hot-middleware@2.x
├─┬ webpack-manifest-plugin@2.2.0 
│ └─┬ fs-extra@7.0.1 
│   ├── jsonfile@4.0.0 
│   └── universalify@0.1.2 
└── UNMET PEER DEPENDENCY webpack-plugin-serve@0.x || 1.x

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/ava/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.2 requires a peer of type-fest@^0.13.1 but none was installed.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.2 requires a peer of webpack-hot-middleware@2.x but none was installed.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.2 requires a peer of webpack-plugin-serve@0.x || 1.x but none was installed.
npm WARN sass-loader@10.2.1 requires a peer of fibers@>= 3.1.0 but none was installed.
npm WARN sass-loader@10.2.1 requires a peer of node-sass@^4.0.0 || ^5.0.0 || ^6.0.0 but none was installed.
npm WARN react-device-detect@1.17.0 requires a peer of react@>= 0.14.0 < 18.0.0 but none was installed.
npm WARN react-device-detect@1.17.0 requires a peer of react-dom@>= 0.14.0 < 18.0.0 but none was installed.
npm WARN react-image@1.5.1 requires a peer of react@^15 || ^16 but none was installed.
npm WARN react-image@1.5.1 requires a peer of react-dom@^15 || ^16 but none was installed.
npm WARN react-tabs@3.0.0 requires a peer of react@^16.3.0 but none was installed.
npm WARN video-react@0.13.9 requires a peer of react@^15.0.0 || ^16.0.0 but none was installed.
npm WARN video-react@0.13.9 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none was installed.
npm WARN @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.24.1 requires a peer of @babel/core@^7.13.0 but none was installed.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none was installed.
npm WARN jest-config@26.6.3 requires a peer of ts-node@>=9.0.0 but none was installed.
npm WARN jsdom@16.7.0 requires a peer of canvas@^2.5.0 but none was installed.
npm WARN ws@7.5.9 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.5.9 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm WARN redux-devtools@3.7.0 requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0 but none was installed.
npm ERR! Linux 6.2.0-36-generic
npm ERR! argv "/home/owlnest/.nvm/versions/node/v6.17.1/bin/node" "/home/owlnest/.nvm/versions/node/v6.17.1/bin/npm" "install"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! path /home/owlnest/timemap/timemap/node_modules/.staging/@types/istanbul-lib-coverage-1d1ed989/package.json
npm ERR! code ENOTDIR
npm ERR! errno -20
npm ERR! syscall open

npm ERR! ENOTDIR: not a directory, open '/home/owlnest/timemap/timemap/node_modules/.staging/@types/istanbul-lib-coverage-1d1ed989/package.json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/owlnest/timemap/timemap/npm-debug.log

**Comment by breezykermo** [comment]
Hi there, thank you for this issue. I have just added a deprecation note to the main README, as we haven't actively maintained this repository for some time. If you'd like to create a project based on the code, then I would suggest that you work from [Bellingcat's fork](https://github.com/bellingcat/ukraine-timemap), which has been more actively maintained.
