### ISSUE TITLE
Remove unnecessary fields in store

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/timemap#33]
There are a bunch of unnecessary fields in [the store](https://github.com/forensic-architecture/timemap/blob/develop/src/store/initial.js) at the moment. We need to clean this fat, and make the store [as shallow as possible](https://juusomikkonen.com/blog/2017/01/22/keeping-redux-state-shallow.html). @francamps is the best to do this, given an understanding of how extant fields were once used in Ayotzinapa.

**Comment by breezykermo** [comment]
I would also be in favour of removing data structures like [the d3 parsers](https://github.com/forensic-architecture/timemap/blob/develop/src/store/initial.js#L149-L151) from the store, relegating this logic to higher-order/curried functions at a component level, or in utilities. This is towards keeping the store as lean as possible.

**Comment by breezykermo** [comment]
@francamps, did you fix this with #11?

**Comment by francamps** [comment]
@breezykermo Yes, that is correct.
