### ISSUE TITLE
Support for Search feature

### ISSUE THREAD

**Issue by francamps** [forensic-architecture/timemap#4]
The Search feature will allow to filter through the fetched domain items (such as `events`) as well as `tags` and `categories` (such as `events`). I suggest searching in memory without fetching for efficiency.
The results should display next the result type (`event`, `tag`, etc), together with its properties.

* If an `event` is found, clicking on the item will i) shift the map anchor to the event and ii) shift the timeline to center the timespan to the time of the `event` found.
* If a `tag` is found, clicking on it will select all domain items tagged with it.
* If a `category` is found, clicking on it will select all domain items tagged with it.

I believe no inconsistencies exist with these rules, but please bring it up if you think you can think of any.

<img width="667" alt="screen shot 2018-10-29 at 5 00 26 pm" src="https://user-images.githubusercontent.com/1273180/47680334-e77e5f00-db9c-11e8-81ae-6985b1fbc382.png">

**Comment by breezykermo** [comment]
inital pass at this added with #151
