### ISSUE TITLE
Narrative lines display when events are not shown

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/timemap#43]
When the timeline is narrowed to filter events (or when a tag is specified), the events disappear from the map:  but the dotted lines that string events together to represent narratives do not.

@francamps, I think that we need to do some more design thinking on narratives; in particular, how they are (or are not) visualised in the map.

I am beginning to think that maybe narratives should not be represented as dotted lines in the map, but that dotted lines (or other visual connections between events) are activated by some other data structure. Not sure what the solution is here, but flagging to start a discussion.

**Comment by francamps** [comment]
Some additional things to consider here:
* Lines between events is only shown in narrative mode. the current narrative should be foregrounded, and the other narratives dimmed.
* Events should have higher z-index than narrative lines.
* An arrowhead styling needs to be added for narrative lines (for narratives that indicate movement).
