### ISSUE TITLE
Standardise JS imports through webpack, and CSS through SCSS imports

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/timemap#51]
Currently a few libraries are imported via CDNs in [index.html](https://github.com/forensic-architecture/timemap/blob/develop/index.html#L6-L10), rather than managed by NPM in package.json. In addition to being messy, this causes 'no undefined' errors to be thrown in JS linting (for the d3 global object).

We should standardiise all imports, for both JS and CSS, through NPM (and import the d3 object in necessary files) so that all dependencies are managed by and processed through Webpack.

**Comment by breezykermo** [comment]
@PhilDenoncourt, if you're looking for another relatively straightforward issue, a PR for this would be much appreciated! Related to #91

**Comment by PhilDenoncourt** [comment]
Will get to it..

**Comment by breezykermo** [comment]
This being treated in #184
