### ISSUE TITLE
If event is selected, timeline zooms should keep it in focus

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/timemap#72]
When an event is selected and the timeline zoom is intensified, the selected event does not stay in focus (unless it happens to be exactly in the middle of the timeline). Zoom modifications of the timeline should gravitate around selected events, keeping them in focus.

**Comment by francamps** [comment]
What does 'the timeline zoom is intensified' mean?

**Comment by francamps** [comment]
Oh, you probably mean the timeline is zoomed in?
So an obvious solution for this would be to automatically center the timeline to any event that is selected. 
In the case of clicking to select a location that contains more than one event, if these events happen at different moments in time, the timeline could extend and center in the middle point in time between all of them.

**Comment by breezykermo** [comment]
Yes sorry, I'm referring to when the timeline zoom moves to a smaller scope, e.g. from 3 years to 3 months.

I think that the centering should take place only when the zoom level is changed (either immediately before or immediately after would work just as well), as it is possible to have a selected event that is not in the center of the map.

In the case of multiple times amongst selected points, I think it would make more sense to me if the _first_ event were the centered one (rather than the middle one).
